### ISSUE TITLE
Low GPU utilization CUDA

### ISSUE THREAD

**Issue by fariedabuzaid** [aai-institute/USFlows#52]
GPU utilization on coda machines is low (5-15%).
There is potentially a bottleneck somewhere
- [x] Data handling?
- [x] All operations performed on gpu?
- [ ] ???

**Comment by giorgiapitteri** [comment]
PR for this issue: #58 

Changes made:
- covariance operations on the device
- all dataset loaded on the device
- batch size increased
-
Max utilization (70%)

It still drops to 7 % sometimes.

**Comment by fariedabuzaid** [comment]
Closing this issue since it was mostly solved by #58
